name: "Release New Version"

on: push
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ZIP_FILE_NAME: logscale_azure_function.zip
      DIR_NAME: azure_function_timer_trigger_code
      JSON_FILE_NAME: arm.json
    steps:
      - uses: actions/checkout@v2
      - name: Install more-utils
        run: sudo apt-get install moreutils
      - name: Set env
        run:  echo RELEASE_VERSION=${GITHUB_REF#refs/*/} >> $GITHUB_ENV && echo $RELEASE_VERSION
      - name: "Create ZIP"
        run: |
          (cd ${{ env.DIR_NAME }} && zip -r ../${{ env.ZIP_FILE_NAME }} .)

      - uses: actions/upload-artifact@v3
        with:
          name: Azure Function zip
          path: ${{ env.ZIP_FILE_NAME }}
      